<?xml version="1.0" encoding="utf-8"?><Database Name="QLKeToan" Class="QuanLy_KeToanDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QLKeToan;Integrated Security=True" SettingsObjectName="QuanLy_KeToan.Properties.Settings" SettingsPropertyName="QLKeToanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Hang" Member="Hangs">
    <Type Name="Hang">
      <Column Name="MaHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiHang" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MaDonViTinh" Storage="_DonViTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MoTaHang" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="VAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThueNhapKhau" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GiamGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Hinh" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Hang_KhoChua" Member="KhoChuas" ThisKey="MaHang" OtherKey="MaHang" Type="KhoChua" Cardinality="One" />
      <Association Name="Hang_ChiTietHDBan" Member="ChiTietHDBans" ThisKey="MaHang" OtherKey="MaHang" Type="ChiTietHDBan" Cardinality="One" />
      <Association Name="Hang_ChiTietHDMua" Member="ChiTietHDMuas" ThisKey="MaHang" OtherKey="MaHang" Type="ChiTietHDMua" Cardinality="One" />
      <Association Name="LoaiHang_Hang" Member="LoaiHang" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoaiHang" IsForeignKey="true" />
      <Association Name="NhaCungCap_Hang" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiHang" Member="LoaiHangs">
    <Type Name="LoaiHang">
      <Column Name="MaLoaiHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiHang" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MoTaLoaiHang" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoaiHang_Hang" Member="Hangs" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="Hang" />
      <Association Name="LoaiHang_NhaCungCap" Member="NhaCungCaps" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="NhaCungCap" Cardinality="One" />
      <Association Name="LoaiHang_KhoHang" Member="KhoHangs" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="KhoHang" />
      <Association Name="LoaiHang_LoHDBan" Member="LoHDBans" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoHDBan" />
      <Association Name="LoaiHang_LoHDMua" Member="LoHDMuas" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoHDMua" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DCNCC" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MaTinh" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SoFax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="NhaCungCap_Hang" Member="Hangs" ThisKey="MaNCC" OtherKey="MaNCC" Type="Hang" />
      <Association Name="NhaCungCap_HoaDonMua" Member="HoaDonMuas" ThisKey="MaNCC" OtherKey="MaNCC" Type="HoaDonMua" />
      <Association Name="LoaiHang_NhaCungCap" Member="LoaiHang" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoaiHang" IsForeignKey="true" />
      <Association Name="TinhThanh_NhaCungCap" Member="TinhThanh" ThisKey="MaTinh" OtherKey="MaTinh" Type="TinhThanh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonViTinh" Member="DonViTinhs">
    <Type Name="DonViTinh">
      <Column Name="MaDonViTinh" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TenDonViTinh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TinhThanh" Member="TinhThanhs">
    <Type Name="TinhThanh">
      <Column Name="MaTinh" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTinh" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MaNuoc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TinhThanh_NhaCungCap" Member="NhaCungCaps" ThisKey="MaTinh" OtherKey="MaTinh" Type="NhaCungCap" />
      <Association Name="TinhThanh_KhachHang" Member="KhachHangs" ThisKey="MaTinh" OtherKey="MaTinhThanh" Type="KhachHang" />
      <Association Name="Nuoc_TinhThanh" Member="Nuoc" ThisKey="MaNuoc" OtherKey="MaNuoc" Type="Nuoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Nuoc" Member="Nuocs">
    <Type Name="Nuoc">
      <Column Name="MaNuoc" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNuoc" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Nuoc_TinhThanh" Member="TinhThanhs" ThisKey="MaNuoc" OtherKey="MaNuoc" Type="TinhThanh" />
    </Type>
  </Table>
  <Table Name="dbo.KhoHang" Member="KhoHangs">
    <Type Name="KhoHang">
      <Column Name="MaKhoHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiHang" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TenKhoHang" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DiaChiKhoHang" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="KhoHang_KhoChua" Member="KhoChuas" ThisKey="MaKhoHang" OtherKey="MaKhoHang" Type="KhoChua" Cardinality="One" />
      <Association Name="KhoHang_ChiTietPhieuXuat" Member="ChiTietPhieuXuats" ThisKey="MaKhoHang" OtherKey="MaKhoHang" Type="ChiTietPhieuXuat" />
      <Association Name="LoaiHang_KhoHang" Member="LoaiHang" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoaiHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhoChua" Member="KhoChuas">
    <Type Name="KhoChua">
      <Column Name="MaKhoHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="KhoHang_KhoChua" Member="KhoHang" ThisKey="MaKhoHang" OtherKey="MaKhoHang" Type="KhoHang" IsForeignKey="true" />
      <Association Name="Hang_KhoChua" Member="Hang" ThisKey="MaHang" OtherKey="MaHang" Type="Hang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhieuXuat" Member="LoaiPhieuXuats">
    <Type Name="LoaiPhieuXuat">
      <Column Name="MaLoaiPhieuXuat" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiPhieuXuat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoaiPhieuXuat_PhieuXuat" Member="PhieuXuats" ThisKey="MaLoaiPhieuXuat" OtherKey="MaLoaiPhieuXuat" Type="PhieuXuat" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKhachHang" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DCKH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MaTinhThanh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SoFax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="KhachHang_HoaDonBan" Member="HoaDonBans" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="HoaDonBan" />
      <Association Name="TinhThanh_KhachHang" Member="TinhThanh" ThisKey="MaTinhThanh" OtherKey="MaTinh" Type="TinhThanh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiHDBan" Member="LoaiHDBans">
    <Type Name="LoaiHDBan">
      <Column Name="MaLoaiHDBan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiHDBan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoaiHDBan_HoaDonBan" Member="HoaDonBans" ThisKey="MaLoaiHDBan" OtherKey="MaLoaiHDBan" Type="HoaDonBan" />
    </Type>
  </Table>
  <Table Name="dbo.TyGiaNgoaiTe" Member="TyGiaNgoaiTes">
    <Type Name="TyGiaNgoaiTe">
      <Column Name="MaTienTe" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ngay" Type="System.DateTime" DbType="SmallDateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TyGia" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TyGiaNgoaiTe_HoaDonBan" Member="HoaDonBans" ThisKey="MaTienTe" OtherKey="MaTienTe" Type="HoaDonBan" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhieuThu" Member="LoaiPhieuThus">
    <Type Name="LoaiPhieuThu">
      <Column Name="MaLoaiPhieuThu" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiPhieuThu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoaiPhieuThu_PhieuThu" Member="PhieuThus" ThisKey="MaLoaiPhieuThu" OtherKey="MaLoaiPhieuThu" Type="PhieuThu" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuThu" Member="PhieuThus">
    <Type Name="PhieuThu">
      <Column Name="MaLoaiPhieuThu" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoThu" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaPhieuThu" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhachHang" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaTienTe" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="GiaTri" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TyGiaNgoaiTe" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GiaTriChuyenDoi" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoaiPhieuThu_PhieuThu" Member="LoaiPhieuThu" ThisKey="MaLoaiPhieuThu" OtherKey="MaLoaiPhieuThu" Type="LoaiPhieuThu" IsForeignKey="true" />
      <Association Name="LoPhieuThu_PhieuThu" Member="LoPhieuThu" ThisKey="MaLoThu" OtherKey="MaLoThu" Type="LoPhieuThu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoPhieuThu" Member="LoPhieuThus">
    <Type Name="LoPhieuThu">
      <Column Name="MaLoThu" Type="System.String" DbType="NChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayThu" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoPhieuThu_PhieuThu" Member="PhieuThus" ThisKey="MaLoThu" OtherKey="MaLoThu" Type="PhieuThu" />
    </Type>
  </Table>
  <Table Name="dbo.LoPhieuXuat" Member="LoPhieuXuats">
    <Type Name="LoPhieuXuat">
      <Column Name="MaLoHDBan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLoXuat" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoPhieuXuat_PhieuXuat" Member="PhieuXuats" ThisKey="MaLoHDBan" OtherKey="MaLoHDBan" Type="PhieuXuat" Cardinality="One" />
      <Association Name="LoHDBan_LoPhieuXuat" Member="LoHDBan" ThisKey="MaLoHDBan" OtherKey="MaLoHDBan" Type="LoHDBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoHDBan" Member="LoHDBans">
    <Type Name="LoHDBan">
      <Column Name="MaLoHDBan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiHang" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgayLoHDBan" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoHDBan_LoPhieuXuat" Member="LoPhieuXuats" ThisKey="MaLoHDBan" OtherKey="MaLoHDBan" Type="LoPhieuXuat" Cardinality="One" />
      <Association Name="LoHDBan_HoaDonBan" Member="HoaDonBans" ThisKey="MaLoHDBan" OtherKey="MaLoHDBan" Type="HoaDonBan" Cardinality="One" />
      <Association Name="LoaiHang_LoHDBan" Member="LoaiHang" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoaiHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonBan" Member="HoaDonBans">
    <Type Name="HoaDonBan">
      <Column Name="MaLoaiHDBan" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoHDBan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHDBan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhachHang" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MaTienTe" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NgayHDBan" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="HoaDonBan_PhieuXuat" Member="PhieuXuats" ThisKey="MaLoHDBan,MaHDBan" OtherKey="MaLoHDBan,MaHDBan" Type="PhieuXuat" Cardinality="One" />
      <Association Name="HoaDonBan_ChiTietHDBan" Member="ChiTietHDBans" ThisKey="MaLoHDBan,MaHDBan" OtherKey="MaLoHDBan,MaHDBan" Type="ChiTietHDBan" Cardinality="One" />
      <Association Name="LoaiHDBan_HoaDonBan" Member="LoaiHDBan" ThisKey="MaLoaiHDBan" OtherKey="MaLoaiHDBan" Type="LoaiHDBan" IsForeignKey="true" />
      <Association Name="LoHDBan_HoaDonBan" Member="LoHDBan" ThisKey="MaLoHDBan" OtherKey="MaLoHDBan" Type="LoHDBan" IsForeignKey="true" />
      <Association Name="TyGiaNgoaiTe_HoaDonBan" Member="TyGiaNgoaiTe" ThisKey="MaTienTe" OtherKey="MaTienTe" Type="TyGiaNgoaiTe" IsForeignKey="true" />
      <Association Name="KhachHang_HoaDonBan" Member="KhachHang" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanQuyen" Member="PhanQuyens">
    <Type Name="PhanQuyen">
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Them" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Sua" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuXuat" Member="PhieuXuats">
    <Type Name="PhieuXuat">
      <Column Name="MaLoaiPhieuXuat" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoHDBan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHDBan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PhieuXuat_ChiTietPhieuXuat" Member="ChiTietPhieuXuats" ThisKey="MaLoHDBan,MaHDBan" OtherKey="MaLoHDBan,MaHDBan" Type="ChiTietPhieuXuat" Cardinality="One" />
      <Association Name="HoaDonBan_PhieuXuat" Member="HoaDonBan" ThisKey="MaLoHDBan,MaHDBan" OtherKey="MaLoHDBan,MaHDBan" Type="HoaDonBan" IsForeignKey="true" />
      <Association Name="LoaiPhieuXuat_PhieuXuat" Member="LoaiPhieuXuat" ThisKey="MaLoaiPhieuXuat" OtherKey="MaLoaiPhieuXuat" Type="LoaiPhieuXuat" IsForeignKey="true" />
      <Association Name="LoPhieuXuat_PhieuXuat" Member="LoPhieuXuat" ThisKey="MaLoHDBan" OtherKey="MaLoHDBan" Type="LoPhieuXuat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhieuXuat" Member="ChiTietPhieuXuats">
    <Type Name="ChiTietPhieuXuat">
      <Column Name="MaLoHDBan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHDBan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhoHang" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PhieuXuat_ChiTietPhieuXuat" Member="PhieuXuat" ThisKey="MaLoHDBan,MaHDBan" OtherKey="MaLoHDBan,MaHDBan" Type="PhieuXuat" IsForeignKey="true" />
      <Association Name="KhoHang_ChiTietPhieuXuat" Member="KhoHang" ThisKey="MaKhoHang" OtherKey="MaKhoHang" Type="KhoHang" IsForeignKey="true" />
      <Association Name="ChiTietHDBan_ChiTietPhieuXuat" Member="ChiTietHDBan" ThisKey="MaLoHDBan,MaHDBan,MaHang" OtherKey="MaLoHDBan,MaHDBan,MaHang" Type="ChiTietHDBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietHDBan" Member="ChiTietHDBans">
    <Type Name="ChiTietHDBan">
      <Column Name="MaLoHDBan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHDBan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="ChiTietHDBan_ChiTietPhieuXuat" Member="ChiTietPhieuXuats" ThisKey="MaLoHDBan,MaHDBan,MaHang" OtherKey="MaLoHDBan,MaHDBan,MaHang" Type="ChiTietPhieuXuat" Cardinality="One" />
      <Association Name="HoaDonBan_ChiTietHDBan" Member="HoaDonBan" ThisKey="MaLoHDBan,MaHDBan" OtherKey="MaLoHDBan,MaHDBan" Type="HoaDonBan" IsForeignKey="true" />
      <Association Name="Hang_ChiTietHDBan" Member="Hang" ThisKey="MaHang" OtherKey="MaHang" Type="Hang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhieuNhap" Member="LoaiPhieuNhaps">
    <Type Name="LoaiPhieuNhap">
      <Column Name="MaLoaiPhieuNhap" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiPhieuNhap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoaiPhieuNhap_PhieuNhap" Member="PhieuNhaps" ThisKey="MaLoaiPhieuNhap" OtherKey="MaLoaiPhieuNhap" Type="PhieuNhap" />
    </Type>
  </Table>
  <Table Name="dbo.LoPhieuNhap" Member="LoPhieuNhaps">
    <Type Name="LoPhieuNhap">
      <Column Name="MaLoHDMua" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLoNhap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoPhieuNhap_PhieuNhap" Member="PhieuNhaps" ThisKey="MaLoHDMua" OtherKey="MaLoHDMua" Type="PhieuNhap" Cardinality="One" />
      <Association Name="LoHDMua_LoPhieuNhap" Member="LoHDMua" ThisKey="MaLoHDMua" OtherKey="MaLoHDMua" Type="LoHDMua" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhap" Member="PhieuNhaps">
    <Type Name="PhieuNhap">
      <Column Name="MaLoaiPhieuNhap" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoHDMua" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHDMua" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PhieuNhap_ChiTietPhieuNhap" Member="ChiTietPhieuNhaps" ThisKey="MaLoHDMua,MaHDMua" OtherKey="MaLoHDMua,MaHDMua" Type="ChiTietPhieuNhap" Cardinality="One" />
      <Association Name="LoaiPhieuNhap_PhieuNhap" Member="LoaiPhieuNhap" ThisKey="MaLoaiPhieuNhap" OtherKey="MaLoaiPhieuNhap" Type="LoaiPhieuNhap" IsForeignKey="true" />
      <Association Name="LoPhieuNhap_PhieuNhap" Member="LoPhieuNhap" ThisKey="MaLoHDMua" OtherKey="MaLoHDMua" Type="LoPhieuNhap" IsForeignKey="true" />
      <Association Name="HoaDonMua_PhieuNhap" Member="HoaDonMua" ThisKey="MaLoHDMua,MaHDMua" OtherKey="MaLoHDMua,MaHDMua" Type="HoaDonMua" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhieuNhap" Member="ChiTietPhieuNhaps">
    <Type Name="ChiTietPhieuNhap">
      <Column Name="MaLoHDMua" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHDMua" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhoHang" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PhieuNhap_ChiTietPhieuNhap" Member="PhieuNhap" ThisKey="MaLoHDMua,MaHDMua" OtherKey="MaLoHDMua,MaHDMua" Type="PhieuNhap" IsForeignKey="true" />
      <Association Name="ChiTietHDMua_ChiTietPhieuNhap" Member="ChiTietHDMua" ThisKey="MaLoHDMua,MaHDMua,MaHang" OtherKey="MaLoHDMua,MaHDMua,MaHang" Type="ChiTietHDMua" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonMua" Member="HoaDonMuas">
    <Type Name="HoaDonMua">
      <Column Name="MaLoaiHDMua" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoHDMua" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHDMua" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MaTienTe" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NgayHDMua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="HoaDonMua_ChiTietHDMua" Member="ChiTietHDMuas" ThisKey="MaLoHDMua,MaHDMua" OtherKey="MaLoHDMua,MaHDMua" Type="ChiTietHDMua" Cardinality="One" />
      <Association Name="HoaDonMua_PhieuNhap" Member="PhieuNhaps" ThisKey="MaLoHDMua,MaHDMua" OtherKey="MaLoHDMua,MaHDMua" Type="PhieuNhap" Cardinality="One" />
      <Association Name="LoHDMua_HoaDonMua" Member="LoHDMua" ThisKey="MaLoHDMua" OtherKey="MaLoHDMua" Type="LoHDMua" IsForeignKey="true" />
      <Association Name="LoaiHDMua_HoaDonMua" Member="LoaiHDMua" ThisKey="MaLoaiHDMua" OtherKey="MaLoaiHDMua" Type="LoaiHDMua" IsForeignKey="true" />
      <Association Name="NhaCungCap_HoaDonMua" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoHDMua" Member="LoHDMuas">
    <Type Name="LoHDMua">
      <Column Name="MaLoHDMua" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiHang" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgayLoHDMua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoHDMua_HoaDonMua" Member="HoaDonMuas" ThisKey="MaLoHDMua" OtherKey="MaLoHDMua" Type="HoaDonMua" Cardinality="One" />
      <Association Name="LoHDMua_LoPhieuNhap" Member="LoPhieuNhaps" ThisKey="MaLoHDMua" OtherKey="MaLoHDMua" Type="LoPhieuNhap" Cardinality="One" />
      <Association Name="LoaiHang_LoHDMua" Member="LoaiHang" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoaiHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiHDMua" Member="LoaiHDMuas">
    <Type Name="LoaiHDMua">
      <Column Name="MaLoaiHDMua" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiHDMua" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoaiHDMua_HoaDonMua" Member="HoaDonMuas" ThisKey="MaLoaiHDMua" OtherKey="MaLoaiHDMua" Type="HoaDonMua" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietHDMua" Member="ChiTietHDMuas">
    <Type Name="ChiTietHDMua">
      <Column Name="MaLoHDMua" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHDMua" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="ChiTietHDMua_ChiTietPhieuNhap" Member="ChiTietPhieuNhaps" ThisKey="MaLoHDMua,MaHDMua,MaHang" OtherKey="MaLoHDMua,MaHDMua,MaHang" Type="ChiTietPhieuNhap" Cardinality="One" />
      <Association Name="HoaDonMua_ChiTietHDMua" Member="HoaDonMua" ThisKey="MaLoHDMua,MaHDMua" OtherKey="MaLoHDMua,MaHDMua" Type="HoaDonMua" IsForeignKey="true" />
      <Association Name="Hang_ChiTietHDMua" Member="Hang" ThisKey="MaHang" OtherKey="MaHang" Type="Hang" IsForeignKey="true" />
    </Type>
  </Table>
</Database>