<?xml version="1.0" encoding="utf-8"?><Database Name="QLKeToan" Class="QuanLy_KeToanDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QLKeToan;Integrated Security=True" SettingsObjectName="QuanLy_KeToan.Properties.Settings" SettingsPropertyName="QLKeToanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Hang" Member="Hangs">
    <Type Name="Hang">
      <Column Name="MaHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiHang" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MaDonViTinh" Storage="_DonViTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MoTaHang" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="VAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThueNhapKhau" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GiamGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Hinh" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Hang_KhoChua" Member="KhoChuas" ThisKey="MaHang" OtherKey="MaHang" Type="KhoChua" Cardinality="One" />
      <Association Name="Hang_ChiTietPhieuNhap" Member="ChiTietPhieuNhaps" ThisKey="MaHang" OtherKey="MaHang" Type="ChiTietPhieuNhap" Cardinality="One" />
      <Association Name="LoaiHang_Hang" Member="LoaiHang" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoaiHang" IsForeignKey="true" />
      <Association Name="NhaCungCap_Hang" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiHang" Member="LoaiHangs">
    <Type Name="LoaiHang">
      <Column Name="MaLoaiHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiHang" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MoTaLoaiHang" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoaiHang_Hang" Member="Hangs" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="Hang" />
      <Association Name="LoaiHang_NhaCungCap" Member="NhaCungCaps" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="NhaCungCap" Cardinality="One" />
      <Association Name="LoaiHang_KhoHang" Member="KhoHangs" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="KhoHang" />
      <Association Name="LoaiHang_LoPhieuNhap" Member="LoPhieuNhaps" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoPhieuNhap" Cardinality="One" />
      <Association Name="LoaiHang_LoPhieuXuat" Member="LoPhieuXuats" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoPhieuXuat" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DCNCC" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MaTinh" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SoFax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="NhaCungCap_Hang" Member="Hangs" ThisKey="MaNCC" OtherKey="MaNCC" Type="Hang" />
      <Association Name="NhaCungCap_PhieuNhap" Member="PhieuNhaps" ThisKey="MaNCC" OtherKey="MaNCC" Type="PhieuNhap" />
      <Association Name="LoaiHang_NhaCungCap" Member="LoaiHang" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoaiHang" IsForeignKey="true" />
      <Association Name="TinhThanh_NhaCungCap" Member="TinhThanh" ThisKey="MaTinh" OtherKey="MaTinh" Type="TinhThanh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonViTinh" Member="DonViTinhs">
    <Type Name="DonViTinh">
      <Column Name="MaDonViTinh" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TenDonViTinh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TinhThanh" Member="TinhThanhs">
    <Type Name="TinhThanh">
      <Column Name="MaTinh" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTinh" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MaNuoc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TinhThanh_NhaCungCap" Member="NhaCungCaps" ThisKey="MaTinh" OtherKey="MaTinh" Type="NhaCungCap" />
      <Association Name="TinhThanh_KhachHang" Member="KhachHangs" ThisKey="MaTinh" OtherKey="MaTinhThanh" Type="KhachHang" />
      <Association Name="Nuoc_TinhThanh" Member="Nuoc" ThisKey="MaNuoc" OtherKey="MaNuoc" Type="Nuoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Nuoc" Member="Nuocs">
    <Type Name="Nuoc">
      <Column Name="MaNuoc" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNuoc" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Nuoc_TinhThanh" Member="TinhThanhs" ThisKey="MaNuoc" OtherKey="MaNuoc" Type="TinhThanh" />
    </Type>
  </Table>
  <Table Name="dbo.KhoHang" Member="KhoHangs">
    <Type Name="KhoHang">
      <Column Name="MaKhoHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiHang" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TenKhoHang" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DiaChiKhoHang" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="KhoHang_KhoChua" Member="KhoChuas" ThisKey="MaKhoHang" OtherKey="MaKhoHang" Type="KhoChua" Cardinality="One" />
      <Association Name="KhoHang_ChiTietPhieuNhap" Member="ChiTietPhieuNhaps" ThisKey="MaKhoHang" OtherKey="MaKhoHang" Type="ChiTietPhieuNhap" />
      <Association Name="KhoHang_ChiTietPhieuNhap1" Member="ChiTietPhieuNhaps1" ThisKey="MaKhoHang" OtherKey="MaKhoHang" Type="ChiTietPhieuNhap" />
      <Association Name="KhoHang_ChiTietPhieuXuat" Member="ChiTietPhieuXuats" ThisKey="MaKhoHang" OtherKey="MaKhoHang" Type="ChiTietPhieuXuat" />
      <Association Name="LoaiHang_KhoHang" Member="LoaiHang" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoaiHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhoChua" Member="KhoChuas">
    <Type Name="KhoChua">
      <Column Name="MaKhoHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="KhoHang_KhoChua" Member="KhoHang" ThisKey="MaKhoHang" OtherKey="MaKhoHang" Type="KhoHang" IsForeignKey="true" />
      <Association Name="Hang_KhoChua" Member="Hang" ThisKey="MaHang" OtherKey="MaHang" Type="Hang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhieuNhap" Member="LoaiPhieuNhaps">
    <Type Name="LoaiPhieuNhap">
      <Column Name="MaLoaiPhieuNhap" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiPhieuNhap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoaiPhieuNhap_PhieuNhap" Member="PhieuNhaps" ThisKey="MaLoaiPhieuNhap" OtherKey="MaLoaiPhieuNhap" Type="PhieuNhap" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhap" Member="PhieuNhaps">
    <Type Name="PhieuNhap">
      <Column Name="MaPhieuNhap" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiPhieuNhap" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoNhap" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgayPhieuNhap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PhieuNhap_ChiTietPhieuNhap" Member="ChiTietPhieuNhaps" ThisKey="MaPhieuNhap,MaLoNhap" OtherKey="MaPhieuNhap,MaLoNhap" Type="ChiTietPhieuNhap" Cardinality="One" />
      <Association Name="LoaiPhieuNhap_PhieuNhap" Member="LoaiPhieuNhap" ThisKey="MaLoaiPhieuNhap" OtherKey="MaLoaiPhieuNhap" Type="LoaiPhieuNhap" IsForeignKey="true" />
      <Association Name="NhaCungCap_PhieuNhap" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" />
      <Association Name="LoPhieuNhap_PhieuNhap" Member="LoPhieuNhap" ThisKey="MaLoNhap" OtherKey="MaLoNhap" Type="LoPhieuNhap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoPhieuNhap" Member="LoPhieuNhaps">
    <Type Name="LoPhieuNhap">
      <Column Name="MaLoNhap" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLoNhap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoPhieuNhap_PhieuNhap" Member="PhieuNhaps" ThisKey="MaLoNhap" OtherKey="MaLoNhap" Type="PhieuNhap" />
      <Association Name="LoaiHang_LoPhieuNhap" Member="LoaiHang" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoaiHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhieuNhap" Member="ChiTietPhieuNhaps">
    <Type Name="ChiTietPhieuNhap">
      <Column Name="MaPhieuNhap" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoNhap" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhoHang" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PhieuNhap_ChiTietPhieuNhap" Member="PhieuNhap" ThisKey="MaPhieuNhap,MaLoNhap" OtherKey="MaPhieuNhap,MaLoNhap" Type="PhieuNhap" IsForeignKey="true" />
      <Association Name="KhoHang_ChiTietPhieuNhap" Member="KhoHang" ThisKey="MaKhoHang" OtherKey="MaKhoHang" Type="KhoHang" IsForeignKey="true" />
      <Association Name="Hang_ChiTietPhieuNhap" Member="Hang" ThisKey="MaHang" OtherKey="MaHang" Type="Hang" IsForeignKey="true" />
      <Association Name="KhoHang_ChiTietPhieuNhap1" Member="KhoHang1" ThisKey="MaKhoHang" OtherKey="MaKhoHang" Type="KhoHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhieuXuat" Member="LoaiPhieuXuats">
    <Type Name="LoaiPhieuXuat">
      <Column Name="MaLoaiPhieuXuat" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiPhieuXuat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoaiPhieuXuat_PhieuXuat" Member="PhieuXuats" ThisKey="MaLoaiPhieuXuat" OtherKey="MaLoaiPhieuXuat" Type="PhieuXuat" />
    </Type>
  </Table>
  <Table Name="dbo.LoPhieuXuat" Member="LoPhieuXuats">
    <Type Name="LoPhieuXuat">
      <Column Name="MaLoXuat" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLoXuat" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoPhieuXuat_PhieuXuat" Member="PhieuXuats" ThisKey="MaLoXuat" OtherKey="MaLoXuat" Type="PhieuXuat" Cardinality="One" />
      <Association Name="LoaiHang_LoPhieuXuat" Member="LoaiHang" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoaiHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhieuXuat" Member="ChiTietPhieuXuats">
    <Type Name="ChiTietPhieuXuat">
      <Column Name="MaPhieuXuat" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoXuat" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhoHang" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PhieuXuat_ChiTietPhieuXuat" Member="PhieuXuat" ThisKey="MaPhieuXuat,MaLoXuat" OtherKey="MaPhieuXuat,MaLoXuat" Type="PhieuXuat" IsForeignKey="true" />
      <Association Name="KhoHang_ChiTietPhieuXuat" Member="KhoHang" ThisKey="MaKhoHang" OtherKey="MaKhoHang" Type="KhoHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuXuat" Member="PhieuXuats">
    <Type Name="PhieuXuat">
      <Column Name="MaPhieuXuat" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiPhieuXuat" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoXuat" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhachHang" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgayPhieuXuat" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PhieuXuat_ChiTietPhieuXuat" Member="ChiTietPhieuXuats" ThisKey="MaPhieuXuat,MaLoXuat" OtherKey="MaPhieuXuat,MaLoXuat" Type="ChiTietPhieuXuat" Cardinality="One" />
      <Association Name="LoPhieuXuat_PhieuXuat" Member="LoPhieuXuat" ThisKey="MaLoXuat" OtherKey="MaLoXuat" Type="LoPhieuXuat" IsForeignKey="true" />
      <Association Name="LoaiPhieuXuat_PhieuXuat" Member="LoaiPhieuXuat" ThisKey="MaLoaiPhieuXuat" OtherKey="MaLoaiPhieuXuat" Type="LoaiPhieuXuat" IsForeignKey="true" />
      <Association Name="KhachHang_PhieuXuat" Member="KhachHang" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKhachHang" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DCKH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MaTinhThanh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SoFax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="KhachHang_PhieuXuat" Member="PhieuXuats" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="PhieuXuat" />
      <Association Name="KhachHang_HoaDonBan" Member="HoaDonBans" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="HoaDonBan" />
      <Association Name="TinhThanh_KhachHang" Member="TinhThanh" ThisKey="MaTinhThanh" OtherKey="MaTinh" Type="TinhThanh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonBan" Member="HoaDonBans">
    <Type Name="HoaDonBan">
      <Column Name="MaHDBan" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiHDBan" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaLoHDBan" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaKhachHang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaTienTe" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayHDBan" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoaiHDBan_HoaDonBan" Member="LoaiHDBan" ThisKey="MaLoaiHDBan" OtherKey="MaLoaiHDBan" Type="LoaiHDBan" IsForeignKey="true" />
      <Association Name="KhachHang_HoaDonBan" Member="KhachHang" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="KhachHang" IsForeignKey="true" />
      <Association Name="TyGiaNgoaiTe_HoaDonBan" Member="TyGiaNgoaiTe" ThisKey="MaTienTe" OtherKey="MaTienTe" Type="TyGiaNgoaiTe" IsForeignKey="true" />
      <Association Name="LoHDBan_HoaDonBan" Member="LoHDBan" ThisKey="MaLoHDBan" OtherKey="MaLoHDBan" Type="LoHDBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiHDBan" Member="LoaiHDBans">
    <Type Name="LoaiHDBan">
      <Column Name="MaLoaiHDBan" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiHDBan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoaiHDBan_HoaDonBan" Member="HoaDonBans" ThisKey="MaLoaiHDBan" OtherKey="MaLoaiHDBan" Type="HoaDonBan" />
    </Type>
  </Table>
  <Table Name="dbo.TyGiaNgoaiTe" Member="TyGiaNgoaiTes">
    <Type Name="TyGiaNgoaiTe">
      <Column Name="MaTienTe" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ngay" Type="System.DateTime" DbType="SmallDateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TyGia" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TyGiaNgoaiTe_HoaDonBan" Member="HoaDonBans" ThisKey="MaTienTe" OtherKey="MaTienTe" Type="HoaDonBan" />
    </Type>
  </Table>
  <Table Name="dbo.LoHDBan" Member="LoHDBans">
    <Type Name="LoHDBan">
      <Column Name="MaLoHDBan" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLoHDBan" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LoHDBan_HoaDonBan" Member="HoaDonBans" ThisKey="MaLoHDBan" OtherKey="MaLoHDBan" Type="HoaDonBan" />
    </Type>
  </Table>
</Database>